name: Run Schedule for GitHub Issues to Notion Sync

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "0 7 * * *"

permissions:
    contents: read

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Run GitHub Issues to Notion Sync
              run: bun start
